import prisma from "../lib/db";

export interface Car {
  id: string;
  image: string;
  title: string;
  model: string;
  engine: string;
  mileage: string;
  fuelType: string;
  date: string;
  Växellåda: "Automatic" | "Manual";
  fordonstyp: "Bil" | "Karavan";
  bränsle: "Diesel" | "Bensin" | "Hybrid" | "Elektrisk";
}

async function getData() {
  const data = await prisma.car.findMany({
    orderBy: {
      createdAt: "desc",
    },
  });

  return data;
}


export function getCarData(): Car[] {
  return [
    {
      id: "001",
      image: "/carD1.avif",
      title: "Audi",
      model: "Q5",
      engine: "Diesel, Automatic, 163 HP",
      mileage: "116,306 km",
      fuelType: "THE",
      date: "09/2015",
      Växellåda: "Automatic",
      fordonstyp: "Karavan",
      bränsle: "Diesel",
    },
    {
      id: "002",
      image: "/carD1.avif",
      title: "BMW",
      model: "X3",
      engine: "Petrol, Manual, 150 HP",
      mileage: "98,500 km",
      fuelType: "THE",
      date: "03/2017",
      Växellåda: "Manual",
      fordonstyp: "Karavan",
      bränsle: "Bensin",
    },
    {
      id: "003",
      image: "/card3.avif",
      title: "Volvo",
      model: "XC60",
      engine: "Hybrid, Automatic, 190 HP",
      mileage: "132,800 km",
      fuelType: "THE",
      date: "07/2019",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Hybrid",
    },
    {
      id: "004",
      image: "/carD1.avif",
      title: "Mercedes",
      model: "GLC",
      engine: "Electric, 204 HP",
      mileage: "74,000 km",
      fuelType: "THE",
      date: "11/2020",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Elektrisk",
    },
    {
      id: "005",
      image: "/carD1.avif",
      title: "Skoda",
      model: "Kodiaq",
      engine: "Diesel, Automatic, 163 HP",
      mileage: "88,900 km",
      fuelType: "THE",
      date: "05/2016",
      Växellåda: "Automatic",
      fordonstyp: "Karavan",
      bränsle: "Diesel",
    },
    {
      id: "006",
      image: "/card3.avif",
      title: "Peugeot",
      model: "3008",
      engine: "Petrol, Manual, 150 HP",
      mileage: "120,110 km",
      fuelType: "THE",
      date: "01/2018",
      Växellåda: "Manual",
      fordonstyp: "Bil",
      bränsle: "Bensin",
    },
    {
      id: "007",
      image: "/carD1.avif",
      title: "VW",
      model: "Tiguan",
      engine: "Diesel, Automatic, 163 HP",
      mileage: "141,300 km",
      fuelType: "THE",
      date: "10/2015",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Diesel",
    },
    {
      id: "008",
      image: "/carD1.avif",
      title: "Audi",
      model: "Q5",
      engine: "Electric, 204 HP",
      mileage: "66,400 km",
      fuelType: "THE",
      date: "12/2021",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Elektrisk",
    },
    {
      id: "009",
      image: "/card3.avif",
      title: "BMW",
      model: "X3",
      engine: "Hybrid, Automatic, 190 HP",
      mileage: "97,120 km",
      fuelType: "THE",
      date: "04/2014",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Hybrid",
    },
    {
      id: "010",
      image: "/carD1.avif",
      title: "Volvo",
      model: "XC60",
      engine: "Petrol, Manual, 150 HP",
      mileage: "114,500 km",
      fuelType: "THE",
      date: "02/2016",
      Växellåda: "Manual",
      fordonstyp: "Bil",
      bränsle: "Bensin",
    },
    {
      id: "011",
      image: "/carD1.avif",
      title: "Mercedes",
      model: "GLC",
      engine: "Diesel, Automatic, 163 HP",
      mileage: "137,700 km",
      fuelType: "THE",
      date: "06/2019",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Diesel",
    },
    {
      id: "012",
      image: "/card3.avif",
      title: "Skoda",
      model: "Kodiaq",
      engine: "Electric, 204 HP",
      mileage: "58,400 km",
      fuelType: "THE",
      date: "08/2022",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Elektrisk",
    },
    {
      id: "013",
      image: "/carD1.avif",
      title: "Peugeot",
      model: "3008",
      engine: "Petrol, Manual, 150 HP",
      mileage: "126,300 km",
      fuelType: "THE",
      date: "01/2017",
      Växellåda: "Manual",
      fordonstyp: "Bil",
      bränsle: "Bensin",
    },
    {
      id: "014",
      image: "/carD1.avif",
      title: "VW",
      model: "Tiguan",
      engine: "Diesel, Automatic, 163 HP",
      mileage: "92,800 km",
      fuelType: "THE",
      date: "03/2018",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Diesel",
    },
    {
      id: "015",
      image: "/card3.avif",
      title: "Audi",
      model: "Q5",
      engine: "Hybrid, Automatic, 190 HP",
      mileage: "111,900 km",
      fuelType: "THE",
      date: "10/2015",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Hybrid",
    },
    {
      id: "016",
      image: "/carD1.avif",
      title: "BMW",
      model: "X3",
      engine: "Diesel, Automatic, 163 HP",
      mileage: "139,700 km",
      fuelType: "THE",
      date: "11/2013",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Diesel",
    },
    {
      id: "017",
      image: "/carD1.avif",
      title: "Volvo",
      model: "XC60",
      engine: "Electric, 204 HP",
      mileage: "77,400 km",
      fuelType: "THE",
      date: "09/2021",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Elektrisk",
    },
    {
      id: "018",
      image: "/card3.avif",
      title: "Mercedes",
      model: "GLC",
      engine: "Petrol, Manual, 150 HP",
      mileage: "118,900 km",
      fuelType: "THE",
      date: "05/2017",
      Växellåda: "Manual",
      fordonstyp: "Bil",
      bränsle: "Bensin",
    },
    {
      id: "019",
      image: "/carD1.avif",
      title: "Skoda",
      model: "Kodiaq",
      engine: "Hybrid, Automatic, 190 HP",
      mileage: "130,600 km",
      fuelType: "THE",
      date: "07/2020",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Hybrid",
    },
    {
      id: "020",
      image: "/carD1.avif",
      title: "Peugeot",
      model: "3008",
      engine: "Diesel, Automatic, 163 HP",
      mileage: "101,200 km",
      fuelType: "THE",
      date: "08/2015",
      Växellåda: "Automatic",
      fordonstyp: "Bil",
      bränsle: "Diesel",
    },
  ];
}